org: srdtrk
app: serverless-bolt-js
service: serverless-bolt-js
frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs14.x
  timeout: 30
functions:
  slack:
    handler: index.handler
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-offline
